---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "Holly Beale"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format: 
  gfm:
    df-print: kable
---

```{r}
library(tidyverse)
library(janitor)
```


# Load previous manifest
```{r}
all_93_samples_sig_manifest <- 
read_tsv("/mnt/data/manifests/batches_1_and_2_sig_manifest.with_genotypes.2025.05.29_22.26.44.tsv",
         col_names = c("id", "genotype"))
```


# Select train/test sets
```{r}
tabyl(all_93_samples_sig_manifest,
      genotype)


# decision, train on 7 u2af1-s34f (64%, 7/11), test on 4
# correspondingly, train on 52 u2af1-wt  (63%, 52/82), test on 30


train_samples <- all_93_samples_sig_manifest  %>%
  group_by(genotype) %>%
  sample_frac(0.63)

tabyl(train_samples,
      genotype)


test_samples <- anti_join(all_93_samples_sig_manifest, 
                          train_samples, 
                          by = 'id')

tabyl(test_samples,
      genotype)

```
# Make train dataset
```{r}

write_tsv(train_samples,
          "/mnt/data/manifests/batches_1_and_2_sig_manifest.59_test.samples_2025.05.29_22.26.44.tsv",
          col_names = FALSE)

```


# generate signature
```{r}
system( command = "
sig_script=/mnt/code/dennisrm_splicedice/splicedice/code/signature.py; echo $sig_script
source_dir=/mnt/output/splicedice/tcga_batches_1_and_2_2025.05.29/; echo $source_dir
allPS_file=${source_dir}/batches_1_and_2_bed_manifest.with_genotypes.2025.05.29_22.26.44_allPS.tsv 
out_dir=/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/
sig_manfiest=/mnt/data/manifests/batches_1_and_2_sig_manifest.59_test.samples_2025.05.29_22.26.44.tsv
time python3 $sig_script compare -p $allPS_file -m $sig_manfiest -o $out_dir
~/alertme.sh",
intern = TRUE)

```
# review sig
```{r}

sig <- read_tsv("/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/.sig.tsv")

head(sig)

```


# Fit beta
```{r}
system( command = "
sig_script=/mnt/code/dennisrm_splicedice/splicedice/code/signature.py; echo $sig_script
source_dir=/mnt/output/splicedice/tcga_batches_1_and_2_2025.05.29/; echo $source_dir
allPS_file=${source_dir}/batches_1_and_2_bed_manifest.with_genotypes.2025.05.29_22.26.44_allPS.tsv 
out_dir=/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/
sig_manfiest=/mnt/data/manifests/batches_1_and_2_sig_manifest.59_test.samples_2025.05.29_22.26.44.tsv
time python3 $sig_script fit_beta -p $allPS_file -s ${out_dir}.sig.tsv -m $sig_manfiest -o $out_dir
~/alertme.sh",
intern = TRUE)

```

# review beta
```{r}

beta_result <- read_tsv("/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/.beta.tsv")

head(beta_result)

```

# Create PS file with only test samples 
note: set na = "nan" to be consistent with data generated by splicedice
```{r}

allPS <- read_tsv("/mnt/output/splicedice/tcga_batches_1_and_2_2025.05.29/batches_1_and_2_bed_manifest.with_genotypes.2025.05.29_22.26.44_allPS.tsv")

test_ps <- allPS %>%
  select(cluster, test_samples$id)

write_tsv(test_ps, 
          "/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/test_allPS.tsv",
          na = "nan")

```

# Query with test set
```{r}

system( command = "
out_dir=/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test
sig_script=/mnt/code/dennisrm_splicedice/splicedice/code/signature.py; echo $sig_script
test_PS=${out_dir}/test_allPS.tsv
beta_file=${out_dir}/.beta.tsv
time python3 $sig_script query -p $test_PS -b $beta_file -o ${out_dir}/find_u2af1_s34f_sig_in_test_set
~/alertme.sh",
intern = TRUE)


```

# review results
```{r}

query_result <- read_tsv("/mnt/output/splicedice/tcga_batches_1_and_2_2025.06.04_train_test/find_u2af1_s34f_sig_in_test_set.pvals.tsv")

head(query_result)

query_result_longer <- query_result %>%
  pivot_longer(-query,
               names_to = "id",
               values_to = "pvalue") %>%
  mutate(pvalue_rounded = round(pvalue, 2))


query_result_longer_with_genotypes <- query_result_longer %>%
  filter(query == "u2af1-s34f_over_u2af1-wt") %>%
  rename(pvalue_for_u2af1_s34f_match = pvalue) %>%
  left_join(all_93_samples_sig_manifest,
            by = join_by(id))



```

# Did query results reflect genotypes?
```{r}
ggplot(query_result_longer_with_genotypes) +
  geom_histogram(aes(x=pvalue_for_u2af1_s34f_match, fill = genotype),
                 bins = 20) +
  scale_fill_brewer(palette = "Set1")
```

```{r}
query_result_longer_with_genotypes %>%
  filter(genotype == "u2af1-s34f",
         pvalue_rounded == 1)


```

