---
title: "`r gsub('.rmarkdown', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "Holly Beale"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format: 
  gfm:
    toc: true
    df-print: kable
---

```{r setup}

library(tidyverse)

```

# Import some data
```{r}
ps_small <- read_tsv("~/downloads/TCGA_LUAD_allPS.tsv.gz", n_max = 10000)


```

```{r}
#ir <- read_tsv("~/downloads/TCGA_LUAD_intron_retention.tsv.gz")
ir_small <- read_tsv("~/downloads/TCGA_LUAD_intron_retention.tsv.gz", n_max = 10000)
```


# Analyze ps values for 10k clusters
```{r}
ps_small_long  <- pivot_longer(ps_small, -cluster)
head(ps_small_long)

per_cluster_vals <- ps_small_long %>%
group_by(cluster) %>%
summarize(n_Nan = sum(is.na(value)),
n_0 = sum(value == 0, na.rm = TRUE),
n_1 = sum(value == 1, na.rm = TRUE))

summary(per_cluster_vals$n_Nan)
summary(per_cluster_vals$n_0)
summary(per_cluster_vals$n_1)




```


```{r}

ggplot(per_cluster_vals) +
  geom_histogram(aes(x=n_Nan))

ggplot(per_cluster_vals) +
  geom_histogram(aes(x=n_0))

ggplot(per_cluster_vals) +
  geom_histogram(aes(x=n_1))

per_cluster_vals %>%
  pivot_longer(-cluster) %>%
  filter(value != 0) %>%
  ggplot() +
  geom_histogram(aes(x = value,
                     fill = name)) +
  scale_fill_brewer(palette = "Set1") +
  facet_wrap(~name)
                    

per_cluster_vals %>%
  pivot_longer(-cluster) %>%
  filter(value != 0) %>%
  ggplot() +
  geom_density(aes(x = value,
                     fill = name)) +
  scale_fill_brewer(palette = "Set1") +
  facet_wrap(~name)
                    
    

```

```{r}
ggplot(ps_small_long) +
  geom_histogram(aes(x=value))
```


# Analyze ps values for 10k junctions
```{r}
ir_small[1:6,1:6]
ir_small_long <- pivot_longer(ir_small, -Junction)
head(ir_small_long)

per_jnx_vals <- ir_small_long %>%
group_by(Junction) %>%
summarize(n_Nan = sum(is.na(value)),
n_0 = sum(value == 0, na.rm = TRUE),
n_1 = sum(value == 1, na.rm = TRUE))

summary(per_jnx_vals$n_Nan)
summary(per_jnx_vals$n_0)
summary(per_jnx_vals$n_1)

```

```{r}

ggplot(per_jnx_vals) +
  geom_histogram(aes(x=n_Nan))

ggplot(per_jnx_vals) +
  geom_histogram(aes(x=n_0))

ggplot(per_jnx_vals) +
  geom_histogram(aes(x=n_1))

per_jnx_vals %>%
  pivot_longer(-Junction) %>%
  filter(value != 0) %>%
  ggplot() +
  geom_histogram(aes(x = value,
                     fill = name)) +
  scale_fill_brewer(palette = "Set1") +
  facet_wrap(~name)
                    

per_jnx_vals %>%
  pivot_longer(-Junction) %>%
  filter(value != 0) %>%
  ggplot() +
  geom_density(aes(x = value,
                     fill = name)) +
  scale_fill_brewer(palette = "Set1") +
  facet_wrap(~name)
                    
    
```

