FROM python:3.8-slim

WORKDIR /opt

RUN apt-get update && apt-get install -y \
    git build-essential pkg-config libhts-dev samtools=1.16.1-1\
    && rm -rf /var/lib/apt/lists/*

ARG SHA1_splicedice="4dd834b953f6ba2d3e220da87c792d454aa649e0"

RUN git clone --depth 2 \
      https://github.com/diekhans/intronProspector.git \
 && cd intronProspector \
 && ./configure \
 && make -j$(nproc) \
 && make install \
 && cd /opt \
 && rm -rf intronProspector

RUN git clone --depth 2 https://github.com/BrooksLabUCSC/splicedice.git splicedice \
 && cd splicedice \
 && git reset --hard $SHA1_splicedice \
 && pip install --no-cache-dir . \
 && cd /opt

RUN apt-get purge -y git build-essential pkg-config \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
